blueprint:
  name: Camera Motion Detection Notification
  description: Send notifications to a mobile device when motion is detected by a camera
  domain: automation
  source_url: https://github.com/home-assistant/blueprints
  author: Your Name
  input:
    alarm_trigger:
      name: Alarm Trigger Boolean
      description: Input boolean that triggers the alarm when motion is detected
      selector:
        entity:
          filter:
            domain: input_boolean
    notification_device:
      name: Notification Device
      description: Mobile device to send notifications to (requires official Home Assistant app)
      selector:
        device:
          filter:
            integration: mobile_app
    camera_entity:
      name: Camera Entity
      description: Camera to capture snapshots
      selector:
        entity:
          filter:
            domain: camera
    snapshot_directory:
      name: Snapshot Directory
      description: Directory to save snapshots (e.g., /config/www)
      selector:
        text:
      default: /config/www
    snapshot_filename:
      name: Snapshot Filename (without extension)
      description: Filename prefix for snapshots
      selector:
        text:
      default: snapshot
    image_base_url:
      name: Image Base URL
      description: Base URL for accessing snapshots (e.g., https://home.wachter.one/local/)
      selector:
        text:
      default: https://home.wachter.one/local/
    notification_title:
      name: Notification Title
      description: Title for the notification
      selector:
        text:
      default: Motion Detected 📸
    notification_message:
      name: Notification Message
      description: Message for the notification
      selector:
        text:
      default: Motion has been detected!

trigger:
  - trigger: state
    entity_id: !input alarm_trigger
    to: "on"
    from: "off"

variables:
  camera_entity: !input camera_entity
  snapshot_directory: !input snapshot_directory
  snapshot_filename: !input snapshot_filename
  image_base_url: !input image_base_url
  notification_title: !input notification_title
  notification_message: !input notification_message
  timestamp: "{{ now().timestamp() | int }}"
  snapshot_file: "{{ snapshot_filename }}_{{ timestamp }}.png"

action:
  - parallel:
    - alias: "Send motion detection notification without image"
      domain: mobile_app
      type: notify
      device_id: !input notification_device
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
      
    - alias: "Capture snapshot from camera"
      action: camera.snapshot
      data:
        filename: "{{ snapshot_directory }}/{{ snapshot_file }}"
      target:
        entity_id: !input camera_entity

  - alias: "Wait for snapshot to be written"
    delay:
      milliseconds: 750

  - alias: "Send motion detection notification"
    domain: mobile_app
    type: notify
    device_id: !input notification_device
    title: "{{ notification_title }}"
    message: "{{ notification_message }}"
    data:
      image: "{{ image_base_url }}{{ snapshot_file }}"

mode: single
